### ISSUE TITLE
Missing definitions in set theory

### ISSUE THREAD

**Issue by FlorianCassayre** [epfl-lara/lisa#10]
The symbol `subset_of` is used in the axiom of the power set, however it does not have a definition (making it unusable).
We should state somewhere that:
```
x sub y  :=  forall z. (z in x) => (z in y)
```
Or alternatively update the axiom of power set to reflect this definition.

Additionally we should add definitions for other standard symbols (singleton set, ordered pair, set operations, etc.).

**Comment by sankalpgambhir** [comment]
Added subset axiom as PR #47 . This covers the power set with the powerAxiom tying it to subset as well.

**Comment by FlorianCassayre** [comment]
Thanks; I will link that issue accordingly.
