### ISSUE TITLE
`InstantiateForall` overloading errors

### ISSUE THREAD

**Issue by sankalpgambhir** [epfl-lara/lisa#120]
The type signature of the deduced tactic `InstantiateForall`:

https://github.com/epfl-lara/lisa/blob/657acdde3aac6f6c52af545238d89c19c3e1e396/lisa-utils/src/main/scala/lisa/utils/tactics/SimpleDeducedSteps.scala#L127

relies on the input `t: Term*`. This seems to work fine when you have a single input, eg:

```scala
andThen(P |- Q) by InstantiateForall(x)
```

but seems to fail on overload resolution with two or more inputs, and coaxing it into recognition hasn't helped:

```scala
andThen(P |- Q) by InstantiateForall(x, y)
andThen(P |- Q) by InstantiateForall(x: Term, y)
andThen(P |- Q) by InstantiateForall(x: Term, y: Term)
andThen(P |- Q) by InstantiateForall(Seq(x: Term, y: Term): _*)
```

As for now, we can get away with doing instantiations one by one, but the tactic is effectively broken at the moment.

**Comment by SimonGuilloud** [comment]
Issue with scala compiler. We should work arround it and either drop overloading or use Seq, or something else. Not ideal but that's life

**Comment by sankalpgambhir** [comment]
This has fixed itself. It was not working after #124, but is now. I assume upstream changes in the compiler?

Anyhow:
```scala
val testTh = Theorem(∀(x, ∀(y, P(x))) |- P(x)) {
    have(∀(x, ∀(y, P(x))) |- ∀(x, ∀(y, P(x)))) by Hypothesis
    thenHave(thesis) by InstantiateForall(x, y)
  }
  ```
  
  Passes:
  ```scala
 Theorem testTh := ∀'x. ∀'y. 'P('x) ⊢ 'P('x)
  ```
