### ISSUE TITLE
instantiatePredicateSchemas does not instantiates VariableFormulaLabels

### ISSUE THREAD

**Issue by lighthea** [epfl-lara/lisa#80]
instantiatePredicateSchemas does not instantiates `VariableFormulaLabels` despite taking `SchematicVarOrPredLabel` as arguments of its substitution map. Can be reproduced with :
```

val a = VariableFormulaLabel("a")
val b = VariableFormulaLabel("b")

isSame(instantiatePredicateSchemas(a(), Map(a -> LambdaTermFormula(Seq(), b()))), a() )

```

**Comment by SimonGuilloud** [comment]
Solved in https://github.com/epfl-lara/lisa/pull/83
