### ISSUE TITLE
Print errors from proof tactics in meaningful way

### ISSUE THREAD

**Issue by SimonGuilloud** [epfl-lara/lisa#85]
THe new tactics can show errors, but they for now do so in a non-useful way. We need to be able to print proofs (with the proof tactics, no just SC) and show there the fault.

**Comment by sankalpgambhir** [comment]
This should be fixed with #99 . Any other additions needed for this, @SimonGuilloud ?

**Comment by sankalpgambhir** [comment]
Fixed with #99 and #101 .
